### ISSUE TITLE
Uniswap getExchange should be called with await

### ISSUE THREAD

**Issue by robertmagier** [HardlyDifficult/hardlydifficult-test-helpers#64]
```
const exchange = protocols.uniswap.getExchange(
  web3,
  tx.logs[0].args.exchange
);

```
should be called with await as
```
const exchange = await protocols.uniswap.getExchange(
  web3,
  tx.logs[0].args.exchange
);
```

I couldn't get exchange.address to use in dai.approve when I was running it without await and this helped to fix my problem.

**Comment by NickCuso** [comment]
Ugh, sorry again!  I'll update the readme.

I think you have worked through it now, but you might want to reference the test file instead.  Both these issues were fine there - I just have not been maintaining the readme correctly..
